# testing using CircleCI orb
# see https://on.cypress.io/circleci-orb

# for non-orb configuration see old commit
# https://github.com/cypress-io/cypress-example-kitchensink/blob/aabb10cc1bb9dee88e1bf28e0af5e9661427ee7a/circle.yml

# to use CircleCI orbs need to use version >= 2.1
version: 2.1
orbs:
  # use Cypress orb from CircleCI registry

  win: circleci/windows@5.1.0


jobs:
  win-test:
    working_directory: ~/app
    executor:
      name: win/default
      size: medium
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Install Node.js v22
          command: |
            nvm install 22
            nvm use 22

      - restore_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm ci
      - run: npm run cy:verify
      - run: npm run cy:info

      - save_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            # could not use environment variables for some reason
            - C:\Users\circleci\AppData\Local\Cypress\Cache
            - C:\Users\circleci\AppData\Roaming\npm-cache

      - run:
          name: 'Start server'
          command: npm run start
          background: true

      - run:
          name: 'Run Cypress tests'
          command: npm run e2e -- --env circle=true
          no_output_timeout: '1m'
      - store_artifacts:
          path: cypress\screenshots

  win-test-chrome:
    working_directory: ~/app
    executor:
      name: win/default
      size: medium
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      # install Chrome browser on Windows machine using Chocolatey
      # https://chocolatey.org/packages/GoogleChrome
      - run: choco install googlechrome --ignore-checksums -y
      - run: npm ci
      - run: npm run cy:verify
      - run: npm run cy:info

      - save_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            # could not use environment variables for some reason
            - C:\Users\circleci\AppData\Local\Cypress\Cache
            - C:\Users\circleci\AppData\Roaming\npm-cache

      - run:
          name: 'Start server'
          command: npm run start
          background: true

      - run:
          name: 'Run Cypress tests'
          command: npm run e2e:chrome -- --env circle=true
          no_output_timeout: '1m'
      - store_artifacts:
          path: cypress\screenshots

  win-test-firefox:
    working_directory: ~/app
    executor:
      name: win/default
      size: medium
      shell: bash.exe
    steps:
      - checkout

      - restore_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      # install Firefox browser on Windows machine using Chocolatey
      # https://chocolatey.org/packages/Firefox
      - run: choco install firefox -y
      - run: npm ci
      - run: npm run cy:verify
      - run: npm run cy:info

      - save_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            # could not use environment variables for some reason
            - C:\Users\circleci\AppData\Local\Cypress\Cache
            - C:\Users\circleci\AppData\Roaming\npm-cache

      - run:
          name: 'Start server'
          command: npm run start
          background: true

      - run:
          name: 'Run Cypress tests'
          command: npm run e2e:firefox -- --env circle=true
          no_output_timeout: '1m'
      - store_artifacts:
          path: cypress\screenshots


workflows:
  win-build:
    jobs:
      - win-test
      - win-test-chrome
      - win-test-firefox
